base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("cart/", include("cart.urls", namespace="cart"))
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, 
                        document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", cart_add, name="cart_add"),
    path("remove/<int:product_id>/", cart_remove, name="cart_remove")
]

main/urls.py
from django.urls import path

from .views import (
    index, product_details,
    shop, category,
    about, contacts
)

app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("shop/", shop, name="shop"),
    path("shop/<slug:category_slug>", category, name="category"),
    path("shop/<slug:category_slug>/<slug:product_slug>",
         product_details, name="product_details"),

    path("about/", about, name="about"),
    path("contacts/", contacts, name="contacts"),
]

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to="categories/", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering=["name"]
        indexes=[models.Index(fields=["name"])]
        verbose_name="Category"
        verbose_name_plural="Categories"

class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to="products/", blank=True)
    descr = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(
        default=0.00,
        max_digits=4,
        decimal_places=2
    )
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="products")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("main:product_details", args=[self.category.slug, self.slug])
    
    def discount_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2) 
        return self.price

    class Meta:
        ordering=["name"]
        indexes=[
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["-created_at"])

            ]
        verbose_name="Product"
        verbose_name_plural="Products"


class Slider(models.Model):
    name=models.CharField(max_length=255)
    descr=models.TextField()
    image=models.ImageField(upload_to="slider/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering=["name"]
        indexes=[
            models.Index(fields=["name"]),
            models.Index(fields=["-created_at"])

            ]
        verbose_name="Slider Item"
        verbose_name_plural="Slider Items"

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd["quantity"],
            override_quantity=cd["override"]
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {"cart": cart})

main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Product, Category, Slider
from cart.forms import CartAddProductForm


def index(request):
    products = Product.objects.filter(discount__gte=1)
    sliders = Slider.objects.all()

    data = {
        "products": products,
        "sliders": sliders
    }
    return render(request, "main/index.html", data)


def shop(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    page = request.GET.get("page", 1)
    paginator = Paginator(products, 6)
    current_page = paginator.page(int(page))

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        paginator = Paginator(products.filter(category=category), 6)
        current_page = paginator.page(int(page))

    data = {
        "category": category,
        "categories": categories,
        "products_qty": products,
        "products": current_page,
    }

    return render(request, "main/shop.html", data)


def category(request, category_slug):
    categories = Category.objects.all()
    category = get_object_or_404(Category, slug=category_slug)
    products = category.products.filter(available=True)
    page = request.GET.get("page", 1)
    paginator = Paginator(products, 6)
    current_page = paginator.page(int(page))

    data = {
        "categories": categories,
        "category": category,
        "products_qty": products,
        "products": current_page,
    }
    return render(request, "main/category.html", data)


def product_details(request, category_slug, product_slug):
    product = get_object_or_404(Product, slug=product_slug, available=True)
    cart_product_form = CartAddProductForm

    data = {
        "product": product,
        "cart_product_form": cart_product_form
    }
    return render(request, "main/product-details.html", data)


def about(request):
    return render(request, "main/about.html")


def contacts(request):
    return render(request, "main/contacts.html")

cart/templates/cart/cart_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Cart {% endblock %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">Shopping Cart</h1>
  </div>

{% endblock header %}

{% block content %}
  <main class="container mx-auto px-4 py-2">
    <div class="bg-emerald-800 rounded-md mb-4">
      {% for item in cart %}
        {% with product=item.product %}
          <div class="p-4">
            <div class="flex gap-4 mb-2">
              <div class="min-w-[64px] h-[64px]">
                {% if product.image %}
                  <img class="w-[64px] h-[64px] object-cover" src="{{product.image.url}}" alt="{{product.name}}">
                {% else %}
                  <img class="w-[64px] h-[64px] object-cover" src="https://thumb.ac-illust.com/b1/b170870007dfa419295d949814474ab2_t.jpeg" alt="{{product.name}}">
                {% endif %}
              </div>
              <h4 class="text-white mb-2">
                <a href="{{product.get_absolute_url}}">
                  {{product.name}}
                </a>
              </h4>
            </div>
            <p class="text-white mb-2">Quantity: {{item.quantity}}</p>
            <div>
              {% if product.discount %}
                <p class="line-through text-gray-400">$ {{product.price}}</p>
                <p class="text-white mb-2">$ {{product.discount_price}}</p>
              {% else %}
                <p class="text-white mb-2">$ {{product.price}}</p>
              {% endif %}
            </div>
            <div>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                {% csrf_token %}
                <input
                  type="submit"
                  value="Remove"
                  class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-600 cursor-pointer"
                >
              </form>
            </div>
          </div>
        {% endwith %}
      {% endfor %}
    </div>

    <div>
      <h5 class="text-2xl">Total Price $ {{cart.get_total_price}}</h5>
    </div>
    <div class="flex gap-4">
      <a href="/shop" class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-800">Continue Shopping</a>

      {% with cart_quantity=cart|length  %}
        {% if cart_quantity > 0 %}
          <a href="#" class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-800">Checkout</a>
        {% endif %}
      {% endwith %}
    </div>
  </main>
{% endblock content %}

main/templates/main/about.html
{% extends "./base.html" %}
{% load static %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">About</h1>
  </div>
{% endblock header %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} {% endblock %}</title>

  {% block slider_css %}
  {% endblock %}
  <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
  <nav class="bg-emerald-800 sticky top-0 z-[2]">
    <div class="container min-h-[90px] mx-auto px-4 py-2 flex justify-between items-center">
      <div>
        <h4>
          <a href="/" class="text-white text-2xl">StoreEVN</a>
        </h4>
      </div>
      <div class="flex items-center gap-8">
        <!-- Cart start -->
        <div>
          <a href="{% url 'cart:cart_detail' %}" class="relative">
            <span class="flex justify-center items-center absolute right-[-12px] top-[-12px] bg-red-600 leading-0 text-white text-[10px] w-5 h-5 rounded-full">
              {% with cart_quantity=cart|length %}
                {% if cart_quantity > 0 %}
                  {{cart_quantity}}
                {% else %}
                  0
                {% endif %}
              {% endwith %}
            </span>
            <svg viewBox="0 0 24 24" width="24" height="24">
              <path class="fill-white" d="M24,3H4.242L4.2,2.649A3,3,0,0,0,1.222,0H0V2H1.222a1,1,0,0,1,.993.883L3.8,16.351A3,3,0,0,0,6.778,19H20V17H6.778a1,1,0,0,1-.993-.884L5.654,15H21.836Z"/>
              <circle class="fill-white" cx="7" cy="22" r="2"/>
              <circle class="fill-white" cx="17" cy="22" r="2"/>
            </svg>
          </a>
        </div>
        <!-- Cart End -->
        <button data-mobileMenuBtn class="min-[768px]:hidden">
          <svg viewBox="0 0 490.667 490.667" width="24" height="24">
            <g class="fill-white">
              <path
                d="M469.333,224h-448C9.551,224,0,233.551,0,245.333c0,11.782,9.551,21.333,21.333,21.333h448   c11.782,0,21.333-9.551,21.333-21.333C490.667,233.551,481.115,224,469.333,224z" />
              <path
                d="M21.333,117.333h448c11.782,0,21.333-9.551,21.333-21.333s-9.551-21.333-21.333-21.333h-448C9.551,74.667,0,84.218,0,96   S9.551,117.333,21.333,117.333z" />
              <path
                d="M469.333,373.333h-448C9.551,373.333,0,382.885,0,394.667C0,406.449,9.551,416,21.333,416h448   c11.782,0,21.333-9.551,21.333-21.333C490.667,382.885,481.115,373.333,469.333,373.333z" />
            </g>
          </svg>
        </button>
        <div 
          data-menuContainer
          class="
            flex items-center jusfity-between gap-8
            max-[768px]:flex-col
            max-[768px]:fixed 
            max-[768px]:left-[-5000px]
            max-[768px]:top-[90px] 
            max-[768px]:p-8 
            max-[768px]:w-full 
            max-[768px]:h-full
            max-[768px]:bg-emerald-800
          "
        >
          <ul class="flex gap-4 z-40 max-[768px]:flex-col max-[768px]:text-center">
            <li>
              <a 
                href="{% url 'main:index' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                Home
              </a>
            </li>
            <li>
              <a 
                href="{% url 'main:shop' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/shop/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                Shop
              </a>
            </li>
            <li>
              <a 
                href="{% url 'main:about' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/about/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                About
              </a>
            </li>
            <li>
              <a 
                href="{% url 'main:contacts' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/contacts/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                Contacts
              </a>
            </li>
          </ul>
          <div>
            <a href="#" 
              class="
                bg-emerald-600 
                rounded-md px-4 
                py-2 text-emerald-200
                transition-color
                duration-300
                hover:bg-emerald-300
                hover:text-emerald-800
              "
            >
              Sign In
            </a>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <header>
    {% block header %}
    {% endblock header %}
  </header>

  {% block content %}
  {% endblock content %}

  <footer></footer>

  <script src="{% static 'js/script.js' %}"></script>
  {% block slider_js %}
  {% endblock slider_js %}
</body>

</html>

main/templates/main/category.html
{% extends "./base.html" %}
{% load static %}

{% block title %}
  StoreEVN | {{category.name}}
{% endblock title %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">{{category.name}}</h1>
  </div>
{% endblock header %}

{% block content %}
  <main>
    <div class="container mx-auto px-4 flex max-[768px]:flex-wrap gap-4 items-start">
      {% include './includes/categories.html' %}
      <div class="basis-auto">
        <h2 class="text-4xl text-center mb-8">All Products</h2>
        <div 
          class="
            grid 
            gap-4 
            grid-cols-3 
            max-[1280px]:grid-cols-2 
            max-[1024px]:grid-cols-1 
            max-[768px]:grid-cols-3
            max-[580px]:grid-cols-2
            max-[480px]:grid-cols-1
          "
        >
          {% for product in products  %}
            <div class="p-4 bg-gray-100 rounded-md">
              <a 
                href="{{product.get_absolute_url}}"
                class="block mb-2 max-h-[300px] overflow-hidden"
              >
                {% if product.image %}
                  <img class="w-full h-full object-cover" src="{{product.image.url}}" alt="{{product.name}}">
                {% else %}
                  <img class="w-full h-full object-cover" src="https://thumb.ac-illust.com/b1/b170870007dfa419295d949814474ab2_t.jpeg" alt="{{product.name}}">
                {% endif %}
              </a>
              <h3>
                <a 
                  class="block text-lg text-blue-600 my-3 hover:text-blue-300 translation-color duration-300" 
                  href="{{product.get_absolute_url}}"
                >
                  {{product.name}}
                </a>
              </h3>
              <p>{{product.descr|truncatewords:10}}</p>
              
              
              {% if product.discount %}
                <p class="line-through">$ {{product.price}}</p>
                <p>$ {{product.discount_price}}</p>
              {% else %}
                <p>$ {{product.price}}</p>
              {% endif %}

              <a 
                class="block text-lg text-blue-600 mt-3 hover:text-blue-300 translation-color duration-300" 
                href="{{product.get_absolute_url}}"
              >
                View Details
              </a>
            </div>
          {% endfor %}
        </div>
        {% include "./includes/paginator.html" %}
      </div>
    </div>
  </main>
{% endblock content %}

main/templates/main/contacts.html
{% extends "./base.html" %}
{% load static %}

{% block title %}
  StoreEVN | Contacts
{% endblock title %}

{% block header %}
  <h1>Contacts</h1>
{% endblock header %}

main/templates/main/includes/categories.html
<div class="basis-80 min-w-[320px] max-[768px]:min-w-[unset] rounded-md max-[1024px]:basis-full bg-emerald-800 p-8">
  <h3 class="text-2xl text-white mb-4">Categories</h3>
  <ul>
    {% if request.get_full_path == "/shop/" %}
      <li>
        <a 
          href="{% url 'main:shop' %}"
          class="block mb-2 text-red-600"
        >
          All
        </a>
      </li>
    {% else %}
      <li>
        <a 
          href="{% url 'main:shop' %}"
          class="block mb-2 text-emerald-200"
        >
          All
        </a>
      </li>
    {% endif %}

    {% for cat in categories %}
      {% if request.get_full_path|slice:"6:" == cat.slug %}
        <li>
          <a 
            href="{% url 'main:category' cat.slug %}"
            class="block mb-2 text-red-600"
          >
            {{cat.name}}
          </a>
        </li>
      
      {% else %}
        <li>
          <a 
            href="{% url 'main:category' cat.slug %}"
            class="block mb-2 text-emerald-200"
          >
            {{cat.name}}
          </a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
</div>

main/templates/main/includes/paginator.html
{% if products_qty|length > 6 %}
  <ul class="flex gap-4 justify-center my-4">
    <li class="{% if not products.has_previous %} pointer-events-none text-gray-700 {% endif %}">
      <a href="{% if products.has_previous %}
           ?page={{ products.previous_page_number }}
        {% endif %}">
        <
      </a>
    </li>

    {% for page in products.paginator.page_range %}
      {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
        <li>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
      {% endif %}
    {% endfor %}

    <li class="{% if not products.has_next %} pointer-events-none text-gray-700 {% endif %}">
      <a href="{% if products.has_next %}
           ?page={{ products.next_page_number }}
        {% endif %}">
        >
      </a>
    </li>
  </ul>
{% endif %}

main/templates/main/index.html
{% extends './base.html' %}
{% load static %}

{% block title %}
  StoreEVN | Home Page
{% endblock %}

{% block slider_css %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
  <style>
    .swiper-pagination span {
      background: #000;
    }
  </style>
{% endblock %}

{% block header %}
  <div class="swiper z-[1]">
    <div class="swiper-wrapper h-[500px]">
      {% for slide in sliders %}
        <div class="swiper-slide relative">
          <div class="w-full h-[500px]">
            <img class="w-full h-[500px] object-cover" src="{{ slide.image.url }}" alt="{{ slide.name }}" />
          </div>

          <div class="absolute top-[180px] left-[180px] max-w-[568px] bg-black/75 text-white p-8 rounded-md max-[768px]:left-[0px] max-[768px]:mx-8 max-[768px]:top-[90px] max-[420px]:top-[16px]">
            <h4 class="text-3xl font-bold mb-2">{{ slide.name }}</h4>
            <p class="">{{ slide.descr }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
  </div>
{% endblock %}

{% block content %}
  <main>
    <div class="container mx-auto px-4 py-2">
      <h2 class="text-4xl text-center my-8">Sale Products</h2>
      <div class="grid gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 my-4">
        {% for product in products %}
          <div class="p-4 bg-gray-100">
            <a href="{{ product.get_absolute_url }}" class="block mb-2 max-w-full max-h-[248px] overflow-hidden">
              {% if product.image %}
                <img class="w-full h-full object-cover" src="{{ product.image.url }}" alt="{{ product.name }}" />
              {% else %}
                <img class="w-full h-full object-cover" src="https://thumb.ac-illust.com/b1/b170870007dfa419295d949814474ab2_t.jpeg" alt="{{ product.name }}" />
              {% endif %}
            </a>
            <h3><a class="block text-lg text-blue-600 my-3 hover:text-blue-300 translation-color duration-300" href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
            <p>{{ product.descr|truncatewords:10 }}</p>

            {% if product.discount %}
              <p class="line-through">$ {{ product.price }}</p>
              <p>$ {{ product.discount_price }}</p>
            {% else %}
              <p>$ {{ product.price }}</p>
            {% endif %}

            <a class="block text-lg text-blue-600 mt-3 hover:text-blue-300 translation-color duration-300" href="{{ product.get_absolute_url }}">View Details</a>
          </div>
        {% endfor %}
      </div>
    </div>
  </main>
{% endblock %}

{% block slider_js %}
  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  <script>
    new Swiper('.swiper', {
      loop: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true
      }
    })
  </script>
{% endblock %}

main/templates/main/product-details.html
{% extends "./base.html" %}
{% load static %}


{% block title %}
  StoreEVN | {{product.name}}
{% endblock title %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">{{product.name}}</h1>
  </div>
{% endblock header %}

{% block content %}
  <main>
    <div class="container mx-auto px-4 py-2">
      <div class="max-w-[568px] h-[568px]">
        {% if product.image %}
          <img class="w-full h-full object-cover" src="{{product.image.url}}" alt="{{product.name}}">
        {% else %}
          <img class="w-full h-full object-cover" src="https://thumb.ac-illust.com/b1/b170870007dfa419295d949814474ab2_t.jpeg" alt="{{product.name}}">
        {% endif %}
      </div>
      {% if product.discount %}
        <p>$ {{product.discount_price}}</p>
      {% else %}
        <p>$ {{product.price}}</p>
      {% endif %}

      <form action="{% url 'cart:cart_add' product.id %}" method="POST">
        <div>
          {% csrf_token %}
          {{cart_product_form}}
        </div>
        <input type="submit" class="block text-white mt-4 w-fit bg-gray-600 px-4 py-2" value="Add To Cart">
      </form>
    </div>
  </main>
{% endblock content %}

main/templates/main/shop.html
{% extends "./base.html" %}
{% load static %}

{% block title %}
  StoreEVN | Shop
{% endblock title %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">Shop</h1>
  </div>
{% endblock header %}

{% block content %}
  <main>
    <div class="container mx-auto px-4 flex max-[768px]:flex-wrap gap-4 items-start">
      {% include './includes/categories.html' %}
      <div class="basis-auto">
        <h2 class="text-4xl text-center mb-8">All Products</h2>
        <div 
          class="
            grid 
            gap-4 
            grid-cols-3 
            max-[1280px]:grid-cols-2 
            max-[1024px]:grid-cols-1 
            max-[768px]:grid-cols-3
            max-[580px]:grid-cols-2
            max-[480px]:grid-cols-1
          "
        >
          {% for product in products  %}
            <div class="p-4 bg-gray-100 rounded-md">
              <a 
                href="{{product.get_absolute_url}}"
                class="block mb-2 max-h-[300px] overflow-hidden"
              >
                {% if product.image %}
                  <img class="w-full h-full object-cover" src="{{product.image.url}}" alt="{{product.name}}">
                {% else %}
                  <img class="w-full h-full object-cover" src="https://thumb.ac-illust.com/b1/b170870007dfa419295d949814474ab2_t.jpeg" alt="{{product.name}}">
                {% endif %}
              </a>
              <h3>
                <a 
                  class="block text-lg text-blue-600 my-3 hover:text-blue-300 translation-color duration-300" 
                  href="{{product.get_absolute_url}}"
                >
                  {{product.name}}
                </a>
              </h3>
              <p>{{product.descr|truncatewords:10}}</p>
              
              
              {% if product.discount %}
                <p class="line-through">$ {{product.price}}</p>
                <p>$ {{product.discount_price}}</p>
              {% else %}
                <p>$ {{product.price}}</p>
              {% endif %}

              <a 
                class="block text-lg text-blue-600 mt-3 hover:text-blue-300 translation-color duration-300" 
                href="{{product.get_absolute_url}}"
              >
                View Details
              </a>
            </div>
          {% endfor %}
        </div>
        {% include "./includes/paginator.html" %}
      </div>
    </div>
  </main>
{% endblock content %}